[package]
name = "url-shorter-frontend"
version = "0.1.0"
authors = [
    "Sasha Yusuk <thepulticula@gmail.com>"
]
edition = "2018"

[dependencies]
yew = "0.17"
muicss-yew = { git = "https://github.com/AlephAlpha/muicss-yew" }
log = "0.4"
wasm-logger = "0.2"
anyhow = "1.0"