name: CI

on: [pull_request]

jobs:
  build:
    name: Test rust ${{ matrix.rust }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        rust: [stable]
        include:
          - conf: run-ubuntu-latest
            target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            sccache-path: /home/runner/.cache/sccache
          - conf: rub-windows-latest
            target: x86_64-pc-windows-msvc
            os: windows-latest
            sccache-path: C:\sccache
          - conf: run-wasm
            target: wasm32-unknown-unknown
            os: ubuntu-latest
            sccache-path: /home/runner/.cache/sccache

    env:
      RUST_BACKTRACE: full
      RUSTC_WRAPPER: sccache
      RUSTV: ${{ matrix.rust }}
      SCCACHE_CACHE_SIZE: 2G
      SCCACHE_DIR: ${{ matrix.sccache-path }}
      SCCACHE_LINK: https://github.com/mozilla/sccache/releases/download
      SCCACHE_VERSION: v0.2.15
    steps:
      - uses: actions/checkout@v2
      - name: Install sccache (ubuntu-latest)
        if: matrix.os == 'ubuntu-latest'
        run: |
          SCCACHE_FILE=sccache-$SCCACHE_VERSION-x86_64-unknown-linux-musl
          mkdir -p $HOME/.local/bin
          curl -L "$SCCACHE_LINK/$SCCACHE_VERSION/$SCCACHE_FILE.tar.gz" | tar xz
          mv -f $SCCACHE_FILE/sccache $HOME/.local/bin/sccache
          chmod a+x $HOME/.local/bin/sccache
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Install sccache (windows-latest)
        if: matrix.os == 'windows-latest'
        run: |
          $SCCACHE_FILE = "sccache-$Env:SCCACHE_VERSION-x86_64-pc-windows-msvc"
          curl -LO "$Env:SCCACHE_LINK/$Env:SCCACHE_VERSION/$SCCACHE_FILE.tar.gz"
          tar xzf "$SCCACHE_FILE.tar.gz"
          echo "$Env:GITHUB_WORKSPACE/$SCCACHE_FILE" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      - name: Install Rust ${{ matrix.rust }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          profile: minimal
          override: true
          target: ${{ matrix.target }}
          components: rustfmt, clippy
      - name: Cache cargo registry
        uses: actions/cache@v2
        continue-on-error: false
        with:
          path: |
            ~/.cargo/registry/cache
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-registry-
      - name: Save sccache
        uses: actions/cache@v2
        continue-on-error: false
        with:
          path: ${{ matrix.sccache-path }}
          key: ${{ runner.os }}-sccache-${{ hashFiles('**/*') }}
          restore-keys: |
            ${{ runner.os }}-sccache-
      - name: Start MongoDB (ubuntu-latest)
        if: matrix.os == 'ubuntu-latest'
        uses: DigiPie/mongo-action@v1.0.1
        with:
          image-version: latest
          port: 27017
      - name: Start MongoDB (windows-latest)
        if: matrix.os == 'windows-latest'
        run: |
          echo "docker run --name mongo -d -p 27017:27017 mongo:latest"
        shell: cmd
      - name: Test MongoDB connection on Ubuntu-latest
        if: matrix.os == 'ubuntu-latest'
        run: sudo mongo localhost:27017
      - name: Test MongoDB connection on Windows-latest
        if: matrix.os == 'windows-latest'
        run: mongo localhost:27017
      - name: Start sccache server
        run: sccache --start-server
      - name: Run CargoFmt
        if: matrix.os == 'ubuntu-latest'
        run: cargo fmt --all -- --check
      - name: Run Clippy
        if: matrix.os == 'ubuntu-latest'
        run: cargo clippy --all-features --all-targets -- -D warnings
      - name: Build release frontend
        if: matrix.conf == 'run-wasm'
        run: cargo build --verbose --manifest-path url-shorter-frontend/Cargo.toml --target wasm32-unknown-unknown --release
      - name: Build release backend
        if: matrix.conf != 'run-wasm'
        run: cargo build --verbose --manifest-path url-shorter-backend/Cargo.toml --release
      - name: Run tests frontend
        if: matrix.conf == 'run-wasm'
        run: cargo test --manifest-path url-shorter-frontend/Cargo.toml --verbose
      - name: Run tests backend
        if: matrix.conf != 'run-wasm'
        run: cargo test --manifest-path url-shorter-backend/Cargo.toml --verbose
      - name: Print sccache stats
        run: sccache --show-stats
      - name: Stop sccache server
        run: sccache --stop-server || true
